### ISSUE TITLE
[Bug] linuxPackages_cachyos-lto.xone fails to compile

### ISSUE THREAD

**Issue by apt-install-coffee** [chaotic-cx/nyx#958]
### What happens?

when building a system with 
`config.boot.kernelPackages = pkgs.linuxPackages_cachyos-lto;`
and
`config.hardware.xone.enable = true;`

build errors which were otherwise fixed [here](https://github.com/NixOS/nixpkgs/blob/5df43628fdf08d642be8ba5b3625a6c70731c19c/pkgs/os-specific/linux/xone/default.nix#L30C1-L34C7) are present.
```
/build/source/bus/bus.c:126:11: error: incompatible function pointer types initializing 'int (*)(struct device *, const struct device_driver *)' with an expression of type>
  126 |         .match = gip_bus_match,
      |                  ^~~~~~~~~~~~~
1 error generated.
make[2]: *** [/nix/store/nryw8ah91pqacqq05jckh2v5g8ni5c9h-linux-6.12.9-dev/lib/modules/6.12.9-cachyos/source/scripts/Makefile.build:229: /build/source/bus/bus.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/build/source/driver/headset.c:93:9: error: call to undeclared function 'snd_pcm_lib_alloc_vmalloc_buffer'; ISO C99 and later do not support implicit function declarations>
   93 |         return snd_pcm_lib_alloc_vmalloc_buffer(sub,
      |                ^
/build/source/driver/headset.c:99:9: error: call to undeclared function 'snd_pcm_lib_free_vmalloc_buffer'; ISO C99 and later do not support implicit function declarations >
   99 |         return snd_pcm_lib_free_vmalloc_buffer(sub);
      |                ^
/build/source/driver/headset.c:160:10: error: use of undeclared identifier 'snd_pcm_lib_get_vmalloc_page'; did you mean 'snd_pcm_lib_malloc_pages'?
  160 |         .page = snd_pcm_lib_get_vmalloc_page,
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                 snd_pcm_lib_malloc_pages
/nix/store/nryw8ah91pqacqq05jckh2v5g8ni5c9h-linux-6.12.9-dev/lib/modules/6.12.9-cachyos/source/include/sound/pcm.h:1315:5: note: 'snd_pcm_lib_malloc_pages' declared here
 1315 | int snd_pcm_lib_malloc_pages(struct snd_pcm_substream *substream, size_t size);
      |     ^
/build/source/driver/headset.c:160:10: error: incompatible function pointer types initializing 'struct page *(*)(struct snd_pcm_substream *, unsigned long)' with an expres>
  160 |         .page = snd_pcm_lib_get_vmalloc_page,
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
4 errors generated.
```

when looking through the build artifacts, it seems none of the patches specified in the package have been applied.

### What is expected to happen?

xone should have been pached to work with 6.12, and build alongside the cachyos-lto kernel.
